### ISSUE TITLE
DOMException: Failed to set the 'adoptedStyleSheets'

### ISSUE THREAD

**Issue by bastifix** [Wanchai/ngx-capture#32]
Hi, I try to implement to ngx-capture in an ionic 6 page, but copying the code in the wright place delivers:

```
Uncaught (in promise) DOMException: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Sharing constructed stylesheets in multiple documents is not allowed
    at addStyle (http://localhost:8101/vendor.js:96476:51)
    at attachStyles (http://localhost:8101/vendor.js:96486:21)
    at updateComponent (http://localhost:8101/vendor.js:97462:9)
    at http://localhost:8101/vendor.js:97453:32
    at then (http://localhost:8101/vendor.js:97597:61)
    at dispatchHooks (http://localhost:8101/vendor.js:97453:12)
    at Array.dispatch (http://localhost:8101/vendor.js:97430:28)
    at consume (http://localhost:8101/vendor.js:98300:21)
    at flush (http://localhost:8101/vendor.js:98315:9)
```

Is this only a problem because I'm using ionic, or do I miss somehting?
Thanks!

**Comment by Wanchai** [comment]
Probably because of Ionic.

Sorry I've never used it. Could you provide an example on stackblitz?

**Comment by nicks258** [comment]
Facing same issue in ionic 5. Any updates?
