### ISSUE TITLE
Use it on ionic v6

### ISSUE THREAD

**Issue by Tixandre** [Wanchai/ngx-capture#39]
Hello, i use the ngx-capture on ionic and i have the error following : 

```
Unhandled Promise rejection: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Sharing constructed stylesheets in multiple documents is not allowed ; Zone: <root> ; Task: null ; Value: DOMException: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Sharing constructed stylesheets in multiple documents is not allowed
    at addStyle (http://localhost/vendor.js:10957:45)
    at attachStyles (http://localhost/vendor.js:10969:19)
    at http://localhost/vendor.js:12111:7
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (http://localhost/vendor.js:122230:24)
    at _next (http://localhost/vendor.js:122252:9)
    at http://localhost/vendor.js:122259:7
    at new ZoneAwarePromise (http://localhost/polyfills.js:1353:33)
    at http://localhost/vendor.js:122248:12
    at updateComponent (http://localhost/vendor.js:12147:17) Error: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Sharing constructed stylesheets in multiple documents is not allowed
    at addStyle (http://localhost/vendor.js:10957:45)
    at attachStyles (http://localhost/vendor.js:10969:19)
    at http://localhost/vendor.js:12111:7
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (http://localhost/vendor.js:122230:24)
    at _next (http://localhost/vendor.js:122252:9)
    at http://localhost/vendor.js:122259:7
    at new ZoneAwarePromise (http://localhost/polyfills.js:1353:33)
    at http://localhost/vendor.js:122248:12
    at updateComponent (http://localhost/vendor.js:12147:17)
```
if you have any suggestion to resolve the problem

**Comment by ozturkkl** [comment]
@Tixandre 
I got the same error, trying to use html2canvas itself but it's acting weird in all browsers except Safari. Getting some weird artifacts with text "normal" when trying to capture with html2canvas directly. Any updated on your end?

**Comment by nicks258** [comment]
Hello @Wanchai any updates on above?
